name: CI
on:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  miri_with_leaks:
    name: Miri checks
    uses: ./.github/workflows/run_miri.yaml
    with:
      MIRIFLAGS: -Zmiri-strict-provenance -Zmiri-symbolic-alignment-check
  miri_without_leaks:
    name: Miri checks, ignoring leaks
    uses: ./.github/workflows/run_miri.yaml
    with:
      MIRIFLAGS: -Zmiri-strict-provenance -Zmiri-symbolic-alignment-check -Zmiri-ignore-leaks
      RUSTFLAGS: --cfg miri_ignore_leaks
