name: Run miri
on:
  workflow_call:
    inputs:
      MIRIFLAGS:
        required: true
        type: string
      RUSTFLAGS:
        required: false
        type: string

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  RUST_BACKTRACE: short

jobs:
  miri:
    name: Run tests (with leak checks)
    runs-on: ubuntu-latest
    env:
      MIRIFLAGS: ${{ inputs.MIRIFLAGS }}
      RUSTFLAGS: ${{ inputs.RUSTFLAGS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: miri
          override: true

      - name: Setup miri
        uses: actions-rs/cargo@v1
        with:
          command: miri
          args: setup

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: miri
          args: test
